### ISSUE TITLE
rtt_rosparam: Add Eigen and KDL types to rtt_rosparam

### ISSUE THREAD

**Issue by jbohren** [jhu-lcsr-forks/rtt_ros_integration#40]
It should be extremely easy: https://github.com/jhu-lcsr-forks/rtt_ros_integration/blob/hydro-devel/rtt_rosparam/src/rtt_rosparam_service.cpp#L217

**Comment by meyerj** [comment]
According to @smits, a `PropertyBagIntrospector` should be used to store and load complex types. This will cover all complex types like Eigen and KDL without patching rtt_rosparam.

On the other hand, the `PropertyBagIntrospector` class is marked as deprecated in the [API documentation](http://www.orocos.org/stable/documentation/rtt/v2.6.x/api/html/classRTT_1_1marsh_1_1PropertyBagIntrospector.html):

> Deprecated:
> DO NOT USE. Will be removed in 2.x release series.

Check [rtt_rosparam_service.cpp](https://github.com/jhu-lcsr-forks/rtt_ros_integration/blob/master/rtt_rosnode/src/rtt_rosparam_service.cpp) in master branch for examples.

**Comment by jbohren** [comment]
Yeah, I avoided it exactly because it was deprecated. Maybe @smits could clear that up.

**Comment by meyerj** [comment]
Added in https://github.com/orocos/rtt_ros_integration/pull/9.
